store: "MyStore"
server:
  port: 8077
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/borsuk_social_core_db
    username: _
    password: _
    platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./data/index
        #            directory:
        #              root: ./data/index
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
  logging:
  level:
    org:
  flyway:
    enabled: true
#      springframework:
#        TRACE
#      hibernate:
#        type: debug
#        type: trace - для просмотра аргументов